const genres = {
    "Action": 1,
    "Adventure": 2,
    "Comedy": 3,
    "Crime": 4,
    "Drama": 5,
    "Fantasy": 6,
    "Historical": 7,
    "Horror": 8,
    "Mystery": 9,
    "Romance": 10,
    "Sci-Fi": 11,
    "Thriller": 12,
    "Western": 13,
    "Biography": 14,
    "Musical": 15,
    "Superhero": 16,
    "Heist": 17,
    "War": 18,
    "Post-Apocalyptic": 19,
    "Spy": 20,
    "Gothic": 21,
    "Urban Fantasy": 22,
    "Sword and Sorcery": 23,
    "Hard Science Fiction": 24,
    "Soft Science Fiction": 25,
    "Cyberpunk": 26,
    "Steampunk": 27,
    "Dystopian": 28,
    "Utopian": 29,
    "Space Opera": 30,
    "Time Travel": 31,
    "Alternate History": 32,
    "Political": 33,
    "Psychological": 34,
    "Fairy Tale": 35,
    "Mythology": 36,
    "Paranormal": 37,
    "Noir": 38,
    "Pulp": 39,
    "Satire": 40,
    "Tragedy": 41,
    "Epic": 42,
    "Magical Realism": 43,
    "Surrealism": 44,
    "Bildungsroman": 45,
    "Metafiction": 46,
    "Neo-noir": 47,
    "Romantic Comedy": 48,
    "Courtroom": 49,
    "Erotica": 50,
    "Dark Fantasy": 51,
    "High Fantasy": 52,
    "Low Fantasy": 53,
    "Paranormal Romance": 54,
    "New Weird": 55,
    "Slipstream": 56,
    "Experimental": 57,
    "Absurdist": 58,
    "New Adult": 59,
    "Chick Lit": 60,
    "Legal Thriller": 61,
    "Medical Thriller": 62,
    "Techno-Thriller": 63,
    "Cozy Mystery": 64,
    "Police Procedural": 65,
    "Historical Romance": 66,
    "Regency Romance": 67,
    "Science Fantasy": 68,
    "New Wave Science Fiction": 69,
    "Solarpunk": 70,
    "Space Western": 71,
    "Sports Drama": 72,
    "Environmental Fiction": 73,
    "Philosophical Fiction": 74,
    "Coming-of-Age": 75,
    "Mythic Fiction": 76,
    "Postmodern Literature": 77,
    "Supernatural Thriller": 78,
    "Urban Legend": 79,
    "Campus Novel": 80,
    "Detective Fiction": 81,
    "Epistolary Novel": 82,
    "Family Saga": 83,
    "Feminist Fiction": 84,
    "Ghost Story": 85,
    "Hardboiled Fiction": 86,
    "Inspirational Fiction": 87,
    "Invasion Literature": 88,
    "Kitchen Sink Realism": 89,
    "Locked Room Mystery": 90,
    "Martial Arts": 91,
    "Mashup": 92,
    "Military Fiction": 93,
    "Nature Writing": 94,
    "Occult Fiction": 95,
    "Picaresque": 96,
    "Planetary Romance": 97,
    "Postcyberpunk": 98,
    "Psychological Thriller": 99,
    "Religious Fiction": 100,
    "Robinsonade": 101,
    "Romantic Suspense": 102,
    "Sea Story": 103,
    "Serial Killer Fiction": 104,
    "Slice of Life": 105,
    "Southern Gothic": 106,
    "Space Exploration": 107,
    "Splatterpunk": 108,
    "Spy Fiction": 109,
    "Superhero Fiction": 110,
    "Swashbuckler": 111,
    "Sword and Planet": 112,
    "Sword and Sandal": 113,
    "Tall Tale": 114,
    "Teen Drama": 115,
    "Treasure Hunt": 116,
    "Vampire Fiction": 117,
    "Weird West": 118,
    "Whodunit": 119,
    "Wuxia": 120,
    "Zombie Fiction": 121,
    "Dieselpunk": 122,
    "Folk Horror": 123,
    "Pirate Fiction": 124,
    "Alien Invasion": 125,
    "Apocalyptic Fiction": 126,
    "Bizarro Fiction": 127,
    "Cli-fi": 128,
    "Conspiracy Thriller": 129,
    "Cosmic Horror": 130,
    "Grimdark": 131,
    "Hardboiled Detective": 132,
    "Medical Drama": 133,
    "Mythopoeia": 134,
    "Prehistoric Fiction": 135,
    "Quest Narrative": 136,
    "Revenge Tragedy": 137,
    "Space Romance": 138,
    "Suburban Gothic": 139
  };

  module.exports = genres;